Print in hello world doesnt have () :) (#233)
File "<ipython-input-9-6bfb78082e8c>", line 2
    print sess.run(hello)
             ^
SyntaxError: invalid syntax